# permissions for end users to edit postgresbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgresbackup-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-backup-azureblob-operator
    app.kubernetes.io/part-of: postgres-backup-azureblob-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresbackup-editor-role
rules:
- apiGroups:
  - database.muntashirislam.com
  resources:
  - postgresbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.muntashirislam.com
  resources:
  - postgresbackups/status
  verbs:
  - get
